name: Subscribe

on:
  workflow_dispatch:
    
  schedule:
    - cron: 0 * * * *
   
jobs:
  AR2A:
    name: Anime RSS to Aria2
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
    - name: Download
      env:
        ARIA2_HOST: ${{ secrets.ARIA2_HOST }}
        ARIA2_PORT: ${{ secrets.ARIA2_PORT }}
        ARIA2_SECRET: ${{ secrets.ARIA2_SECRET }}
      run: |
        python ./main.py || echo 'Check your configuration.'
    - name: Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Subscription
        skip_dirty_check: false
